title: Aymeric Beaumet
description: >-
  Aymeric is a Senior Software Engineer with years of experience deploying and
  maintaining resilient, scalable and highly available backend systems. He now
  spends most of his time working with Go, Rust and Kubernetes.
url: "https://aymericbeaumet.com"
baseurl: "/"
permalink: /:title
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
