theme: minima

title: Aymeric Beaumet
tagline: Thoughts, Notes & Tips
description: >-
  Aymeric is a Senior Software Engineer with years of experience deploying and
  maintaining resilient, scalable, and highly available backend systems. He now
  spends most of his time working with Go, Rust, and Kubernetes.
url: "https://aymericbeaumet.com"
social:
  name: Aymeric Beaumet
  links:
    - https://github.com/aymericbeaumet/
    - https://stackoverflow.com/users/1071486/aymericbeaumet?tab=profile
    - https://keybase.io/aymericbeaumet/
    - https://www.linkedin.com/in/aymericbeaumet/

disqus:
  shortname: aymericbeaumet

baseurl: "/"
permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
